version: '3'
services:
  app:
    container_name: fampay-test
    restart: always
    build: .
    ports:
      - '3000:3000'
    external_links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'